name: vpinball
version: '10.8.1-git'
summary: Pinball table editor and simulator
description: |
  Just a test

confinement: devmode
base: core22

parts:
  vpinball:
    source: .
    plugin: cmake
    #plugin: nil
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      # - "-- -j$(nproc)"
    build-packages:
      - automake
      - bison
      - unzip
      - libtool
      - cmake
      - zlib1g-dev
      - libdrm-dev
      - libgbm-dev
      - libglu1-mesa-dev
      - libegl-dev
      - libudev-dev
      - libx11-dev
      - libxrandr-dev
      - libwayland-dev
    stage-packages:
        - zlib1g
        - libdrm2
        - libgbm1
        - libglu1-mesa
        - libegl1
        - libudev1
        - libx11-6
        - libxrandr2
        - libwayland-client0
        # bass dependencies
        - libasound2
        - libpulse0
        # how do we add pipewire?
    override-pull: |
      craftctl default
      # We need latest cmake for the external libs and for the main build
      apt-get install -y ca-certificates gpg wget
      wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
      echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
      apt-get update
      apt-get install -y cmake
      cd standalone/linux
      ./external.sh
      cd ../..
      cp standalone/cmake/CMakeLists_gl-linux-x64.txt CMakeLists.txt

apps:
  vpinball:
    command: /usr/local/VPinballX_GL
    plugs:
      - home
      - x11
      - wayland
      - opengl
      - alsa
      - pulseaudio
      - audio-playback
